### ISSUE TITLE
eslintrcの整理

### ISSUE THREAD

**Issue by zackey1514** [ottaaa/merch#14]
# ゴール

eslintのルールを整理する。
- スタイル系
- tsdoc系(鬱陶しくない程度に)
- 整理したtsconfigに合わせる

# やるべきこと/方針
※肥大化したら issue を分けてね

- [ ] TODO

**Comment by ottaaa** [comment]
#13 もだけど front/backend 横串で設定できたら(できるのか？)嬉しいなという気持ちがあります

**Comment by zackey1514** [comment]
ちょっと調べてみたけど、ベースの設定を用意して各自に当てるって形でできそう
[パッケージで管理する方法](https://zenn.dev/shinnoki/articles/3f008f53b2312f) がイケてそうなのでちょっとやってみます～

**Comment by zackey1514** [comment]
と思ったけどapiとfrontでコンテナ分けてるんだった

**Comment by ottaaa** [comment]
おっ、調査ありがとう！
merch 直下に置いてあげればなんとかなりそうだね
